{{- if .Values.serviceAccount.enabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "microservice-template.serviceAccountName" . }}
  labels:
    app: {{ template "microservice-template.name" . }}
    chart: {{ template "microservice-template.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- end -}}
