{{- if .Values.serviceMonitor.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ template "microservice-template.fullname" . }}
  labels:
    app: {{ template "microservice-template.name" . }}
    chart: {{ template "microservice-template.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  endpoints:
    - path: /metrics
      port: http
      interval: {{ .Values.serviceMonitor.interval }}
  selector:
    matchLabels:
      app: {{ template "microservice-template.fullname" . }}
{{- end }}
